### PR TITLE
Update the code for fluorescence deconvolution

### PR DESCRIPTION
**Pull request by lihaoyeh**
Building on top of Cam's initial framework, this PR includes the following additional feature:

1. 2D/3D multi-channel fluorescence deconvolution is implemented
2. z-padding is included to avoid z-boundary artifacts
3. An example notebook is provided to explain how to properly call the functions

### CODE REVIEW

**Review by camFoltz — COMMENTED** [review]
This all looks good to me.  I like how you extended it to include multiple wavelengths.  I think it is important to specify in the documentation that the order of the `I_Fluor` needs to match the order of the `lambda_emiss` to match the fluroescence channel with the proper wavelength.

**Comment by camFoltz** [comment]
Also, I noticed the `opencv-python` is not a dependency of waveorder.  Do you think you can add this in for this PR?

**Review by camFoltz — APPROVED** [review]

**Review by camFoltz — APPROVED** [review]

**Comment by lihaoyeh** [comment]
> This all looks good to me. I like how you extended it to include multiple wavelengths. I think it is important to specify in the documentation that the order of the `I_Fluor` needs to match the order of the `lambda_emiss` to match the fluroescence channel with the proper wavelength.

I have added documentation in the deconvolution functions and the constructor to note that the order of values in `bg_level`, `reg`, and `lambda_emiss` need to match the order of the first index of `I_fluor`.

**Comment by lihaoyeh** [comment]
> Also, I noticed the `opencv-python` is not a dependency of waveorder. Do you think you can add this in for this PR?
> 
> Not necessarily relevant to this code, but will be helpful for the QLIPP workshop on friday, as reconstruction cannot be run without cv2

I have tried adding `opencv-python` in the requirment list of `setup.py` file. It will run the installation fine on my local computer (mac). However, this step will affect the installation of waveorder on IBM machine. This is because that `setup.py` installs packages from `pip`. `pip` does not hold a power-pc compiled file for proper installation and then the `waveorder` installation will fail due to not being able to install `opencv-python`. I can install `opencv` with conda on IBM machine, so I leave this requirement out and install it later manually. Do you think adding `opencv-python` as a requirement on `recOrder` will work for the workshop on Friday? Sorry for the inconvenience.

**Comment by camFoltz** [comment]
> I have tried adding `opencv-python` in the requirment list of `setup.py` file. It will run the installation fine on my local computer (mac). However, this step will affect the installation of waveorder on IBM machine. This is because that `setup.py` installs packages from `pip`. `pip` does not hold a power-pc compiled file for proper installation and then the `waveorder` installation will fail due to not being able to install `opencv-python`. I can install `opencv` with conda on IBM machine, so I leave this requirement out and install it later manually. Do you think adding `opencv-python` as a requirement on `recOrder` will work for the workshop on Friday? Sorry for the inconvenience.

No Problem -- this looks good.

**Review by camFoltz — APPROVED** [review]

**Pull request merged**
